<a href="https://colab.research.google.com/github/aruntakhur/SitareUniversity/blob/main/DropOut_NN_DL_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
import pandas as pd

# Set random seed for reproducibility
np.random.seed(42)

# 1. Original activations (10 units)
y = np.array([2, 3, 5, 4, 6, 1, 7, 3, 2, 5])

# 2. Dropout parameters
q = 0.8  # keep probability

# 3. Compute original variance across units
original_variance = np.var(y, ddof=0)


In [6]:
num_samples = 10  # number of dropout samples

In [7]:
# 4. Simulate inverted dropout
dropout_samples = []
for _ in range(num_samples):
    mask = np.random.binomial(1, q, size=y.shape)
    y_drop = (mask / q) * y
    dropout_samples.append(y_drop)

In [8]:
dropout_samples

[array([2.5 , 3.75, 6.25, 5.  , 7.5 , 1.25, 8.75, 3.75, 2.5 , 6.25]),
 array([2.5 , 3.75, 6.25, 0.  , 0.  , 0.  , 8.75, 3.75, 2.5 , 6.25]),
 array([2.5 , 3.75, 6.25, 0.  , 7.5 , 1.25, 8.75, 3.75, 2.5 , 6.25]),
 array([0.  , 3.75, 0.  , 0.  , 7.5 , 0.  , 8.75, 3.75, 2.5 , 6.25]),
 array([2.5 , 3.75, 0.  , 5.  , 7.5 , 1.25, 8.75, 0.  , 2.5 , 0.  ]),
 array([2.5 , 3.75, 6.25, 0.  , 7.5 , 1.25, 8.75, 3.75, 2.5 , 6.25]),
 array([0.  , 3.75, 6.25, 5.  , 7.5 , 1.25, 8.75, 3.75, 0.  , 6.25]),
 array([2.5 , 3.75, 6.25, 5.  , 7.5 , 1.25, 8.75, 3.75, 2.5 , 6.25]),
 array([2.5 , 3.75, 6.25, 5.  , 0.  , 1.25, 8.75, 3.75, 2.5 , 6.25]),
 array([2.5 , 3.75, 0.  , 0.  , 7.5 , 0.  , 0.  , 3.75, 0.  , 6.25])]

In [12]:
# 5. Compute empirical variance per unit
empirical_variance = np.var(dropout_samples, axis=0, ddof=0)

# 6. Compute theoretical variance per unit
theoretical_variance = ((1 - q) / q) * y**2

# 7. Prepare a table
table = pd.DataFrame({
    "Unit": np.arange(1, len(y)+1),
    "Original Activation": y,
    "Empirical Variance": np.round(empirical_variance, 3),
    "Theoretical Variance": np.round(theoretical_variance, 3)
})

# 8. Print results
print(f"Original variance across units (before dropout): {original_variance:.3f}\n")
print(table)

Original variance across units (before dropout): 3.360

   Unit  Original Activation  Empirical Variance  Theoretical Variance
0     1                    2               1.000                  1.00
1     2                    3               0.000                  2.25
2     3                    5               8.203                  6.25
3     4                    4               6.250                  4.00
4     5                    6               9.000                  9.00
5     6                    1               0.328                  0.25
6     7                    7               6.891                 12.25
7     8                    3               1.266                  2.25
8     9                    2               1.000                  1.00
9    10                    5               3.516                  6.25
